language: python
group: travis_latest

git:
  depth: 25
  quiet: true



matrix:
  include:
  - os: linux
    python: 3.6
   
   
  - os: linux
    python: 3.6
    compiler: clang
    env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:

  - eval "${MATRIX_EVAL}"

install: 

  - export CXX=clang-6.0 CC=clang-6.0     
  - pip install -r requirements.txt --upgrade 
script:
  - python --version
  - python setup.py install
  - py.test


notifications:
  email: false 




