language: python
group: travis_latest

git:
  depth: 25
  quiet: true



matrix:
  include:
  - os: linux
    python: 3.6

   
  - os: osx
    language: minimal
    python: 3.6
  
install:  pip install -r requirements.txt --upgrade 

script:
  - python setup.py install
  - py.test


notifications:
  email: false 




