language: python
group: travis_latest

git:
  depth: 25
  quiet: true



matrix:
  include:
  - os: linux
    python: 3.6
   
   
  - os: linux
    python: 3.6
    compiler: clang

  - os: osx
    osx_image: xcode8.3
    python: 3.6

    
before_install:

  - eval "${MATRIX_EVAL}"

install: 
  - pip install -r requirements.txt --upgrade 

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
	
	- python3 --version
	- python3 setup.py install
	- py.test
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
	
	- python --version
	- python setup.py install
	- py.test
    fi
  
notifications:
  email: false 




