language: python
group: travis_latest

git:
  depth: 25
  quiet: true



matrix:
  include:
  - os: linux
    python: 3.6
    install: 
	- pip install -e .[tests]
	- pip install -r requirements.txt --upgrade 
   
  - os: linux
    python: 3.6
    compiler: clang
    install: 
	- pip install -e .[tests]
	- pip install -r requirements.txt --upgrade 
  - os: osx
    language: minimal
    install: 
	- pip3 install -e .[tests]
	- pip3 install -r requirements.txt --upgrade 

before_install:

  - eval "${MATRIX_EVAL}"

script:

  - python --version
  - python setup.py install
  - py.test


notifications:
  email: false 




