language: python
group: travis_latest

git:
  depth: 25
  quiet: true



matrix:
  include:
  - os: linux
    python: 3.6
   
   
  - os: linux
    python: 3.6
    compiler: clang

  - os: osx
    osx_image: xcode8
    language: generic
    python: 3.6
    compiler: clang
    
before_install:

  - eval "${MATRIX_EVAL}"

install: 
  - pip install -r requirements.txt --upgrade 

script:

  - python --version
  - python setup.py install
  - py.test


notifications:
  email: false 




