language: python
group: travis_latest

git:
  depth: 25
  quiet: true



matrix:
  include:
  - os: linux
    python: 3.6

   
  - os: osx
    osx_image: xcode9.4
    language: generic
    python: 3.6
    env: TOXENV=py36

before_install:

  - eval "${MATRIX_EVAL}"
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then python -m pip install --upgrade setuptools ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then python -m pip install --upgrade pip ; fi

install:  
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew upgrade python
    fi
  - pip install -r requirements.txt --upgrade 
script:
  - python --version
  - python setup.py install
  - py.test


notifications:
  email: false 




