language: python

sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'gcc-5']
      env:
        - CXX='g++-5'
        - CC='gcc-5'
      python: 2.7
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'gcc-5']
      env:
        - CXX='g++-5'
        - CC='gcc-5'
      python: 3.5
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'gcc-5']
      env:
        - CXX='g++-5'
        - CC='gcc-5'
      python: 3.6

    - os: osx
      osx_image: xcode11
      language: generic
      env:
        - PYTHON=3.2

    - os: osx
      osx_image: xcode11
      language: generic
      env:
        - PYTHON=3.6


before_install:
    - eval "${MATRIX_EVAL}"

install:
  - pip install -r requirements.txt --upgrade
  - python --version

script:
  - python setup.py install
  - py.test

notifications:
  email: false 
