language: python
group: travis_latest

git:
  depth: 25
  quiet: true

python:
- 3.7
- 3.6

matrix:
  include:
  - os: linux
    python: 3.7

   
  - os: osx
    language: minimal

  
install:  pip install -r requirements.txt --upgrade

script:
  - python setup.py install
  - py.test


notifications:
  email: false 




