language: python

sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc47
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'gcc-7']
      env:
        - CXX='g++-7'
        - CC='gcc-7'
      python: 2.7
    - os: linux
      compiler: gcc
      addons: &gcc47
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'gcc-7']
      env:
        - CXX='g++-7'
        - CC='gcc-7'
      python: 3.5
    - os: linux
      compiler: gcc
      addons: &gcc47
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'gcc-7']
      env:
        - CXX='g++-7'
        - CC='gcc-7'
      python: 3.6

    - os: osx
      osx_image: xcode11
      language: generic
      env:
        - MATRIX_EVAL="brew install gcc7 && CC=gcc-7 && CXX=g++-7"
        - TOXENV=py32

    - os: osx
      osx_image: xcode11
      language: generic
      env:
        - MATRIX_EVAL="brew install gcc7 && CC=gcc-7 && CXX=g++-7"
        - TOXENV=py36


before_install:
    - eval "${MATRIX_EVAL}"

install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        if [ "$PY" = "3" ]; then
          brew update && brew upgrade python
        fi
    fi
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        export CXX=g++-7 CC=gcc-7;
        # manually install python on osx
        pip install -r requirements.txt --upgrade
    fi
  - pip install -r requirements.txt --upgrade
  - python --version

script:
  - python setup.py install
  - py.test

notifications:
  email: false 
