language: python

sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'gcc-4.9']
      env:
        - CXX='g++-4.9'
        - CC='gcc-4.9'
      python: 2.7
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'gcc-4.9']
      env:
        - CXX='g++-4.9'
        - CC='gcc-4.9'
      python: 3.5
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'gcc-4.9']
      env:
        - CXX='g++-4.9'
        - CC='gcc-4.9'
      python: 3.6
    - os: osx
      osx_image: xcode7.3
      env: PYTHON=2.7 CPP=14 CLANG CMAKE=1
    - os: osx
      osx_image: xcode9
      env: PYTHON=3.6 CPP=14 CLANG DEBUG=1

install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        if [ "$PY" = "3" ]; then
          brew update && brew upgrade python
        else
          curl -fsSL https://bootstrap.pypa.io/get-pip.py | $PY_CMD - --user
        fi
      fi
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        export CXX=clang++ CC=clang;
        # manually install python on osx
        brew update
        brew install python3
        brew reinstall gcc
        virtualenv venv
        source venv/bin/activate
        pip install -r requirements.txt --upgrade
    fi
  - pip install -r requirements.txt --upgrade
  - python --version

script:
  - python setup.py install
  - py.test

notifications:
  email: false 
