language: python
group: travis_latest

git:
  depth: 25
  quiet: true



matrix:
  include:
  - os: linux
    python: 3.6
   
   
  - os: linux
    python: 3.6
    compiler: clang

  - os: linux
    python: 3.6
    before_install:
	  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
	  - chmod +x miniconda.sh
	  - ./miniconda.sh -b
	  - export PATH=/home/travis/miniconda/bin:$PATH
	  - conda update --yes conda  # Update CONDA without command line prompt


before_install:

  - eval "${MATRIX_EVAL}"

install: 
  - pip install -r requirements.txt --upgrade 

script:

  - python --version
  - python setup.py install
  - py.test


notifications:
  email: false 




